[features]
seeds = false
[programs.localnet]
solana_twitter = "G6ycZVGm49zgCyPzkyQTXrxFDUxi9wTzgDAZ7C7VWntU"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/guetteluis/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
